apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-e2e
  namespace: poc-uat
spec:
  releaseName: azure-keyvault-e2e
  interval: 1m
  chart:
    spec:
      chart: azure-keyvault-e2e
      version: "1.0.0"
      sourceRef:
        kind: GitRepository
        name: poc-flux-repo
        namespace: flux-system
  values:
    image:
      repository: saipocregistry.azurecr.io/azure-keyvault-e2e
      tag: latest
    env:
      SPRING_PROFILES_ACTIVE: uat
    replicaCount: 2
